### ISSUE TITLE
brain-ci: stress_test.zig не компилируется — Registry потерял поле claims

### ISSUE THREAD

**Issue by gHashTag** [gHashTag/trinity-fpga#791]
`stress_test.zig` does not compile — 13 errors, all the same:

```
src/brain/stress_test.zig:60:61: error: no field named 'claims' in struct 'basal_ganglia.Registry'
```

## Why it surfaced only now

The `🧪 Stress Test (Functional MRI)` job in `brain-ci` had not run for months —
it sat behind a `needs:` on a health check that returned `NotImplemented`. After
#777 the five unit-test regions and Integration started running, and Stress Test
reached execution for the first time and failed.

This is **not a regression from #777**: under `src/brain/` that branch changed
only `intraparietal_sulcus.zig`.

## What happened

`stress_test.zig` was written against a `Registry` that had a `claims` field,
and nothing has compiled it since the field went away. The test never noticed.

## Two ways to resolve

1. Restore `claims` on `basal_ganglia.Registry`, if it belongs there.
2. Rewrite `stress_test.zig` against the current `Registry` API.

The second is more likely, but that is a question for whoever knows why the
field was removed.

## Related class

Same root as `test-hslm` and `intraparietal_sulcus` (#776): a job muted behind a
`needs:` long enough for the code under it to drift out of compiling. Three
instances from one root in one repository — worth checking the remaining
`needs:` guards in `brain-ci` for the same thing.
